name: well_com_rea
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.0.0
  video_player: ^2.2.18
  http: 0.13.6
  sqflite: ^2.0.0
  riverpod: ^2.4.9
  provider: ^6.1.1
  firebase_messaging: ^14.7.9
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  flutter_sound: ^9.2.13
  microphone: ^0.1.0
  easy_localization: ^3.0.3
  googleapis: ^4.0.0
  googleapis_auth: ^1.4.1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Hosto.png
    - images/Logo.jpg
    - images/Well.jpg
    - images/A.png
    - images/Feed/centre.jpg
    - images/Feed/Alim.png
    - images/Feed/Alim1.jpg
    - images/Feed/Alim2.jpg
    - images/Feed/Alim4.jpg
    - images/Feed/Alim5.jpg
    - images/Feed/Alim6.png
    - images/Health/Centre.png
    - images/Health/H1.png
    - images/Health/H2.jpg
    - images/Health/I1.jpg
    - images/Health/I2.jpg
    - images/Health/I2.png
    - images/Health/I3.jpg
    - images/Health/I4.jpg
    - images/Health/I5.jpg
    - images/Health/I6.jpg
    - images/Health/I6.png
    - images/Health/S1.jpg
    - images/Health/S2.jpg
    - images/Health/S3.jpg
    - images/Health/S4.jpg
    - images/Health/S5.png
    - images/Health/H3.gif
    - images/Health/H4.png
    - images/Douche/Centre.jpg
    - images/Douche/D1.jpg
    - images/Douche/D2.jpg
    - images/Douche/D3.jpg
    - images/Douche/D4.png
    - images/Douche/D5.jpg
    - images/Douche/D6.png
    - images/Bien/Centre.jpg
    - images/Bien/B1.png
    - images/Bien/B2.jpg
    - images/Bien/B3.png
    - images/Bien/B4.jpg
    - images/Bien/B5.jpg
    - images/Bien/B6.jpg
    - images/Bien/B7.jpg
    - images/Bien/B8.png
    - images/Bien/B9.png
    - images/Bien/B10.jpg
    - images/Bien/B11.jpg
    - images/Bien/B12.png
    - images/Health/CentreI.jpg
    - images/Health/CentreS.jpg
    - images/Pain/D0.jpg
    - images/Pain/D2.jpg
    - images/Pain/D4.jpg
    - images/Pain/D6.jpg
    - images/Pain/D8.jpg
    - images/Pain/D10.jpg
    - images/Pain/ManDos.png
    - images/Pain/ManDoul.jpg
    - images/Pain/ManFace.jpg
    - images/Pain/ManProfil.jpg
    - images/Pain/ManProfil.png
    - images/Pain/P1.jpg
    - images/Pain/P2.png
    - images/Pain/P3.jpg
    - images/Pain/P4.png
    - images/Pain/P5.jpg
    - images/Pain/P6.png
    - images/Pain/Pinterro.png
    - images/Pain/Pousse.png
    - images/Pain/PousseV.png
    - images/Installation/I1.png
    - images/Installation/I2.png
    - images/Installation/I3.png
    - images/Installation/I4.png
    - images/Installation/I5.png
    - images/Installation/I6.png
    - images/Installation/I7.png
    - images/Installation/I8.png
    - images/Installation/I9.png
    - images/Installation/I10.png
    - images/Installation/I11.png
    - images/Installation/I12.png
    - images/Installation/I13.png
    - images/Installation/I14.png
    - images/Installation/I15.png
    - images/Installation/I16.png
    - images/Installation/I17.png
    - images/Installation/I18.png
    - images/Soignant/S2.png
    - images/Soignant/S1.jpg
    - images/Soignant/S3.png
    - images/Soignant/S4.png
    - images/Soignant/S5.png
    - images/Soignant/S6.jpg
    - images/Soignant/S7.jpg
    - images/Soignant/S8.png
    - images/Soignant/S9.png
    - images/Soignant/S10.png
    - images/Soignant/S11.png
    - images/Soignant/S12.png
    - images/Soignant/S13.png
    - images/Soignant/S14.png
    - images/Soignant/S15.png
    - images/Soignant/S16.jpg
    - images/Soignant/S17.png
    - images/Soignant/S18.jpg
    - images/Soignant/S19.png
    - images/Soignant/S20.jpg
    - images/Soignant/S21.jpg
    - images/Soignant/S22.png
    - images/Soignant/S23.jpg
    - images/Soignant/S25.png
    - images/Soignant/S26.png
    - images/Soignant/S27.png
    - images/Soignant/S28.png
    - images/Soignant/S29.png
    - images/Soignant/S30.png
    - images/Soignant/S31.png
    - images/Soignant/S32.png
    - images/Soignant/S33.png
    - images/Soignant/S34.png
    - images/Soignant/S35.png
    - images/Soignant/S35.jpg
    - images/Soignant/S36.jpg
    - images/Soignant/S36.png
    - images/Soignant/S37.png
    - images/Soignant/S38.png
    - images/Soignant/S39.png
    - images/Soignant/S40.jpg
    - images/Soignant/S41.png
    - images/Soignant/S42.jpg
    - images/Soignant/S43.png
    - images/Soignant/S44.png
    - images/Soignant/S45.png
    - images/Soignant/S46.jpg
    - images/Discomfort/Centre.jpg
    - images/Discomfort/Dis1.png
    - images/Discomfort/Dis2.png
    - images/Discomfort/Dis3.jpg
    - images/Discomfort/Dis3.png
    - images/Discomfort/Dis4.png
    - images/Discomfort/Dis5.png
    - images/Discomfort/Dis6.jpg
    - images/Discomfort/Dis7.png
    - images/Discomfort/Dis8.jpg
    - images/Discomfort/Dis8.png
    - images/Discomfort/Dis9.png
    - images/Discomfort/Dis10.png
    - images/Discomfort/Dis11.png
    - images/Discomfort/Dis12.png
    - images/Discomfort/Dis13.jpg
    - images/Discomfort/Dis13.png
    - images/Discomfort/Dis14.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
